name: agro_app
description: A new Flutter Agro application for Shopping .

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_pro: ^1.0.0 #no indention
  firebase_auth: ^0.6.6 #Firebase Authentication
  cloud_firestore: ^0.8.2 #cloud_firestore
  google_sign_in: ^5.0.1  #google_sign_in
  shared_preferences: ^2.0.5 #shared_preferences
  fluttertoast: ^8.0.3 #fluttertoast



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
      # Agro Products Section
      #Banners
    - images/Agro_Images/Banners/Agri-Blog-Cover.png
    - images/Agro_Images/Banners/Beans Banner.png
    - images/Agro_Images/Banners/Indian Farmer.jpg
    - images/Agro_Images/Banners/product-banner.jpg
    - images/Agro_Images/Banners/sprinkler.jpg
    - images/Agro_Images/Banners/fertilizer-dealers.webp

      #Categories Icons

    - images/Agro_Images/Categories/agriculture.png
    - images/Agro_Images/Categories/agronomy.png
    - images/Agro_Images/Categories/farmer.png
    - images/Agro_Images/Categories/greenhouse.png
    - images/Agro_Images/Categories/harvest.png
    - images/Agro_Images/Categories/location.png
    - images/Agro_Images/Categories/nitrates-free.png
    - images/Agro_Images/Categories/seed.png
    - images/Agro_Images/Categories/seedling.png

    #Agro Products
    - images/Agro_Images/acidifying_agents/SEARLESS , sulphur powder,500mg.jpg
    - images/Agro_Images/acidifying_agents/WELLNWSS , ultra acid, 100 capsules.jpg
    - images/Agro_Images/acidifying_agents/BASF , ammonium chloride ,1kg powder.jpg
    - images/Agro_Images/acidifying_agents/AQUA, otirinse , 237ml liquid.jpg
    - images/Agro_Images/Fertilizers/ABTEC , vermi compost , 5kg powder.jpg
    - images/Agro_Images/pesticides/EXPERT, pest fix,250ml liquid.jpg
    - images/Agro_Images/pesticides/ZAENA, biofungi, 100.jpg
    - images/Agro_Images/Soil_conditioners/ORGANIC, green sand,1kg powder.jpg
    - images/Agro_Images/Soil_conditioners/SOOTHLAND, jump start,1L LIQUID.jpg
    - images/Agro_Images/Soil_conditioners/ENCAP, gypsum,2.5lbs powder.jpg
    - images/Agro_Images/Soil_conditioners/HOFFMAN, peat moss,500mg powder.jpg
    - images/Agro_Images/Soil_conditioners/FERRY MORSE , sunny meadows mox ,700mg powder.jpg




     #Other Products

    - images/c1.jpg
    - images/IMG_1266.JPG
    - images/m1.jpeg
    - images/m2.jpg
    - images/m2.jpg
    - images/w1.jpeg
    - images/w3.jpeg
    - images/w3.jpeg
    - images/cats/tshirt.png
    - images/cats/dress.png
    - images/cats/formal.png
    - images/cats/informal.png
    - images/cats/shoe.png
    - images/cats/jeans.png
    - images/cats/accessories.png
    - images/products/blazer1.jpeg
    - images/products/dress1.jpeg
    - images/products/blazer2.jpeg
    - images/products/hills1.jpeg
    - images/products/hills2.jpeg
    - images/products/skt1.jpeg
    - images/products/skt2.jpeg
    - images/products/dress1.jpeg
    - images/products/dress2.jpeg
    
    
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
